# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3413d0a7946b89e8bb471f5dba2788624d838ec9327dd5ccb9d4f3bbc43cef11968485373e2c475540b787d55f8a0b8fe7ed44181436379aaa238bc860e5ac1d

test:
  secret_key_base: 48fb626eef5eaa7cbbd9d5511dcefca5659f03679990997716b5e533d40472ff35141adaf05bded7c98c88599674cf1192d5182b2a7cf4bbc035f49275c29854

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
